// Methods
import '/imports/api/methods/Sample'; // Load Sample Collection Methods (demonstration)
import '/imports/api/methods/CreateUsers';
import '/imports/api/methods/Accounts/MergeGoogleAccount';
import '/imports/api/methods/Accounts/AddGoogleAccount';
import '/imports/api/methods/UpdateFields';
import '/imports/api/methods/Accounts/ValidateMissingGoogle';
import '/imports/api/methods/Accounts/ValidateEmailUserNameStage';
import '/imports/api/methods/Accounts/ValidateCreatePasswordStage';
import '/imports/api/methods/Accounts/ValidateBasicInfoStage';
import '/imports/api/methods/Accounts/ForgotPassword';
import '/imports/api/methods/Accounts/ExtendLoginExpiration';
import '/imports/api/methods/Accounts/DeleteUserAccount';
import '/imports/api/methods/SkillTree';
import './methods/Subscriptions';
import '/imports/api/methods/SkillForest';
import '/imports/api/methods/Proof';
import '/imports/api/methods/Upload';
import '/imports/api/methods/skillTreeMethods';
import '/imports/api/methods/Comments';
import '/imports/api/methods/Forum';
import '/imports/api/methods/AdminDashboard/SaveEditCommunityMember';
import '/imports/api/methods/AdminDashboard/RoleApplications';
import '/imports/api/methods/imageUpload';
import '/imports/api/methods/Events';
