name: Lint Check

on:
  push: {} #all
  pull_request: {} #all

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Run Setup
        run: devbox run setup

      - name: Run ESLint
        run: devbox run lint # uncomment if you want warnings to cause a fail: -- --max-warnings=0

      - name: Run Prettier
        run: devbox run format
