name: Mocha tests

on:
    push: {} #all
    pull_request: {} #all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'
  
        - name: Install Meteor
          run: curl https://install.meteor.com/ | sh
  
        - name: Install dependencies
          run: npm install
  
        - name: Run Meteor tests
          run: npm test
